### ISSUE TITLE
服务器网站无法登录

### ISSUE THREAD

**Issue by winic57** [egdw/mobile_monitor_android_simple#1]
推送到服务器.通过账户和密码进行登陆.地址在[登陆地址]:https://www.hdy.im/mobile
登录地址不能登陆了

**Comment by egdw** [comment]
您好，这个simple现在是只支持简单的微信通信。网页查看功能已经阉割掉了。原来的项目里有，只是我已经不更新了。
具体使用方法请看这个网页
https://www.52pojie.cn/thread-830341-1-1.html

**Comment by winic57** [comment]
这个项目废弃了？

**Comment by egdw** [comment]
> 这个项目废弃了？

这个项目一直都可以用啊.只是有网页查看的不维护了.
