### ISSUE TITLE
用一两天之后另一个手机就收不到任何通知了，不知道为什么，重新设置也不行。

### ISSUE THREAD

**Issue by zzp654** [egdw/mobile_monitor_android_simple#4]
麻烦恶搞大大帮忙解答下

**Comment by egdw** [comment]
进程被杀了?

**Comment by zzp654** [comment]
> 前进被杀了吗？

不清楚，我也不太懂这些编程这些，只知道我的苹果手机收不到通知了。。

**Comment by egdw** [comment]
> > 前进被杀了吗？
> 
> 不清楚，我也不太懂这些编程这些，只知道我的苹果手机收不到通知了。。

点击测试发送按钮也发不出去了?你联网了吗?是不是断网了?

**Comment by zzp654** [comment]
> > > 前进被杀了吗？
> > 
> > 
> > 显而易见，我也不太懂这些编程这些，只知道我的苹果手机收不到通知了。。
> 
> 点击测试发送按钮也发不出去了？你联网了吗？是不是断网了？

测试发送是可以的，但是其他通知收不到，没有断网

**Comment by egdw** [comment]
> 测试发送是可以的，但是其他通知收不到，没有断网

那应该就是权限问题了,你要么卸载了之后重装有一下,重启一下机子再看看

**Comment by egdw** [comment]
> > > > 前进被杀了吗？
> > > 
> > > 
> > > 显而易见，我也不太懂这些编程这些，只知道我的苹果手机收不到通知了。。
> > 
> > 
> > 点击测试发送按钮也发不出去了？你联网了吗？是不是断网了？
> 
> 测试发送是可以的，但是其他通知收不到，没有断网

把能给这个app开的权限都放行,加入白名单.有些手机还有耗能检测之类的,都加入白名单.

**Comment by zzp654** [comment]
> > 测试发送是可以的，但是其他通知收不到，没有断网
> 
> 那应该就是权限问题了,你要么卸载了之后重装有一下,重启一下机子再看看

哦哦，知道了，那我试一下，还有就是麻烦问一下，需要一直保持软件的界面么？

**Comment by egdw** [comment]
> > > 测试发送是可以的，但是其他通知收不到，没有断网
> > 
> > 
> > 那应该就是权限问题了,你要么卸载了之后重装有一下,重启一下机子再看看
> 
> 哦哦，知道了，那我试一下，还有就是麻烦问一下，需要一直保持软件的界面么？

不用,但是要保持后台能够运行.

**Comment by zzp654** [comment]
> > > > 测试发送是可以的，但是其他通知收不到，没有断网
> > > 
> > > 
> > > 那应该就是权限问题了,你要么卸载了之后重装有一下,重启一下机子再看看
> > 
> > 
> > 哦哦，知道了，那我试一下，还有就是麻烦问一下，需要一直保持软件的界面么？
> 
> 不用,但是要保持后台能够运行.

好的，感谢大佬，这个软件真的很好很方便，谢谢！
